-- MySQL Script generated by MySQL Workbench
-- vie 22 dic 2017 14:06:21 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema elgastodb
-- -----------------------------------------------------
-- base de datos de registro de gastos
DROP SCHEMA IF EXISTS `elgastodb` ;

-- -----------------------------------------------------
-- Schema elgastodb
--
-- base de datos de registro de gastos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elgastodb` DEFAULT CHARACTER SET utf8 ;
USE `elgastodb` ;

-- -----------------------------------------------------
-- Table `elgastodb`.`adm_indefi_ventagasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`adm_indefi_ventagasto` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`adm_indefi_ventagasto` (
  `cod_indicador` VARCHAR(40) NOT NULL COMMENT 'Indicador de llave primaria',
  `cod_entidad` VARCHAR(40) NULL DEFAULT NULL,
  `mon_gastototal` VARCHAR(40) NULL DEFAULT NULL,
  `mon_ventatotal` VARCHAR(40) NULL DEFAULT NULL,
  `fecha_mes` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMM',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'yyyymmdd . codger . intranet quien lo creo',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'yyyymmdd . codger . intranet quien altero',
  PRIMARY KEY (`cod_indicador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elgastodb`.`adm_juridico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`adm_juridico` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`adm_juridico` (
  `cod_juridico` VARCHAR(40) NOT NULL COMMENT 'codigo proveedor o ente juridico',
  `cod_rif` VARCHAR(40) NULL DEFAULT NULL COMMENT 'rif de esta razon social',
  `des_razonsocial` VARCHAR(400) NULL DEFAULT NULL COMMENT 'razon social o nombre de la empresa',
  `tipo_juridico` VARCHAR(40) NULL DEFAULT NULL,
  `estado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ACTIVO|CERRADO si cerrado debe tener fecha cerrado',
  `fecha_creado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD cuando abrio o empezo ser legal',
  `fecha_cerrado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD cuando cerro o dejo de funcionar',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD.codger.sello.intranetoidusuario',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_juridico`))
ENGINE = InnoDB
COMMENT = 'un ente juridico o personal de cada rif DATO SENSIBLE (prove';


-- -----------------------------------------------------
-- Table `elgastodb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`categoria` (
  `cod_categoria` VARCHAR(40) NOT NULL COMMENT 'CATYYYYMMDDhhmmss',
  `des_categoria` VARCHAR(400) NOT NULL COMMENT 'descripcion o nombre categoria',
  `tipo_categoria` VARCHAR(40) NULL DEFAULT 'NORMAL' COMMENT 'ADMINISTRATIVO|NORMAL',
  `fecha_categoria` VARCHAR(40) NULL DEFAULT NULL COMMENT 'fecha creacion al usuario',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien altero YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB
COMMENT = 'nivel 1 clasificacion gasto';


-- -----------------------------------------------------
-- Table `elgastodb`.`entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`entidad` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`entidad` (
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'codger entidad o id sucursal',
  `abr_entidad` VARCHAR(40) NOT NULL COMMENT 'abrebiacion de esta entidad',
  `abr_zona` VARCHAR(40) NOT NULL COMMENT 'siglas de la zona geografica',
  `des_entidad` VARCHAR(400) NOT NULL COMMENT 'descripcion sucursal',
  `status` VARCHAR(40) NOT NULL COMMENT 'ACTIVA|CERRADA|SUSPENDIDA|ESPECIAL',
  `tipo_entidad` VARCHAR(40) NULL DEFAULT 'SUCURSAL' COMMENT 'ADMINISTRATIVA|SUCURSAL',
  `cod_fondo` VARCHAR(40) NULL DEFAULT NULL COMMENT 'fondo o monto disponible si aplica',
  `sello` VARCHAR(40) NULL DEFAULT NULL COMMENT 'sello asociado oasis',
  `rif_sucursal` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Rif razon social',
  `rif_razonsocial` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Nombre razon social',
  `des_administradora` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Nombre del usuario administradora',
  `num_telefonofijo` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Numero telefono fijo',
  `des_nombreenc1` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Nombre encargado o jefe',
  `num_celularenc1` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Numero telefono encargado o jefe',
  `des_nombreenc2` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Nombre segundo encargado',
  `num_celularenc2` VARCHAR(40) NULL DEFAULT NULL COMMENT 'Numero Telefono segundo',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien altero YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`cod_entidad`))
ENGINE = InnoDB
COMMENT = 'las entidades que se le adjudican gastos';


-- -----------------------------------------------------
-- Table `elgastodb`.`entidad_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`entidad_usuario` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`entidad_usuario` (
  `intranet` VARCHAR(40) NOT NULL COMMENT 'usuario relacionado',
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'entidad asociado',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien altero YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`intranet`, `cod_entidad`))
ENGINE = InnoDB
COMMENT = 'relacion usuario contra entidad que adjudica gastos';


-- -----------------------------------------------------
-- Table `elgastodb`.`fondo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`fondo` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`fondo` (
  `cod_fondo` VARCHAR(40) NOT NULL COMMENT 'FONYYYYMMDDhhmmss',
  `fecha_fondo` VARCHAR(40) NOT NULL COMMENT 'por cada codigo hay una fecha y monto',
  `mon_fondo` DECIMAL(20,2) NOT NULL COMMENT 'monto adjudicado a la fecha',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'si alguien lo modifico a mano',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien lo hizo YYYYMMDDhhmmss+.+codger+.+user',
  PRIMARY KEY (`cod_fondo`, `fecha_fondo`))
ENGINE = InnoDB
COMMENT = 'fondos de montos manejados';


-- -----------------------------------------------------
-- Table `elgastodb`.`gas_registro_gastos_ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`gas_registro_gastos_ingreso` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`gas_registro_gastos_ingreso` (
  `cod_registro` VARCHAR(40) NOT NULL COMMENT 'GASYYYYMMDDhhmmss usa fecha y hora',
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'codger de la entidad al cual se le adjudica',
  `cod_categoria` VARCHAR(40) NOT NULL COMMENT 'categoria del egreso o gasto',
  `cod_juridico` VARCHAR(40) NULL COMMENT 'codigo id del proveedor del bien en que se gasta',
  `mon_registro` DECIMAL(20,2) NOT NULL COMMENT 'monto de cuanto se gasto',
  `des_concepto` VARCHAR(800) NOT NULL COMMENT 'descripcion del gasto',
  `tipo_concepto` VARCHAR(40) NULL DEFAULT 'SUCURSAL' COMMENT 'ADMINISTRATIVO|SUCURSAL',
  `des_detalle` VARCHAR(800) NULL DEFAULT NULL COMMENT 'detalle opcional del gasto',
  `des_estado` VARCHAR(800) NULL DEFAULT NULL COMMENT 'porque cambio de estado',
  `estado` VARCHAR(40) NULL DEFAULT 'PENDIENTE' COMMENT 'APROBADO|PENDIENTE|INVALIDO',
  `factura_tipo` VARCHAR(40) NOT NULL DEFAULT 'CONTRIBUYENTE' COMMENT 'ESPECIAL|CONTRIBUYENTE',
  `factura_rif` VARCHAR(40) NULL DEFAULT NULL COMMENT 'rif si factura es contribuyente',
  `factura_num` VARCHAR(40) NULL DEFAULT NULL COMMENT 'mumero de factura opcinal',
  `factura_bin` VARCHAR(800) NULL DEFAULT NULL COMMENT 'ruta de factura por defecto si la sube, es una factura o archivo por gasto',
  `fecha_gastado` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD de cuadno es el gasto registrado',
  `fecha_registro` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD de cuando se creo cada entrada',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien modifico YYYYMMDDhhmmss + codger + . + ficha',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien lo creo YYYYMMDDhhmmss + codger + . + ficha',
  PRIMARY KEY (`cod_registro`))
ENGINE = InnoDB
COMMENT = 'registros gastado por ingreso de bienes por descripcion y monto';


-- -----------------------------------------------------
-- Table `elgastodb`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`log` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`log` (
  `cod_log` CHAR(40) NOT NULL COMMENT 'LOGyyyymmddhhmmss',
  `operacion` VARCHAR(400) NULL DEFAULT NULL COMMENT 'en que modulo controlador y que realizo... y que tablas afecto',
  `sessionficha` CHAR(40) NULL DEFAULT NULL COMMENT 'quien hizo que YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`cod_log`))
ENGINE = InnoDB
COMMENT = 'tabla de chismoso, cada operacion se graba aqui';


-- -----------------------------------------------------
-- Table `elgastodb`.`registro_errado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`registro_errado` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`registro_errado` (
  `cod_registro` VARCHAR(40) NOT NULL COMMENT 'codigo del registro gasto corregir',
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'entidad la cual se le exige corregir',
  `intranet` VARCHAR(40) NOT NULL COMMENT 'usuario que cometio el error (puede este en mas de una entidad)',
  `msg_errado` VARCHAR(40) NULL DEFAULT NULL,
  `msg_enviar` VARCHAR(40) NULL DEFAULT NULL COMMENT 'si ya se envio un correo',
  `sessionerror` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien erro y cuando YYYYMMDDhhmmss + codger + . + ficha',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien lo creo YYYYMMDDhhmmss + codger + . + ficha',
  PRIMARY KEY (`cod_registro`))
ENGINE = InnoDB
COMMENT = 'notificaciones de auditoria a errores cargados por usuarios';


-- -----------------------------------------------------
-- Table `elgastodb`.`registro_gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`registro_gastos` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`registro_gastos` (
  `cod_registro` VARCHAR(40) NOT NULL COMMENT 'GASYYYYMMDDhhmmss usa fecha y hora',
  `cod_entidad` VARCHAR(40) NOT NULL COMMENT 'codger de la entidad al cual se le adjudica',
  `cod_categoria` VARCHAR(40) NOT NULL COMMENT 'categoria del gasto',
  `cod_subcategoria` VARCHAR(40) NOT NULL COMMENT 'cual subcategoria no puede faltar',
  `mon_registro` DECIMAL(20,2) NOT NULL COMMENT 'monto de cuanto se gasto',
  `des_concepto` VARCHAR(8000) NOT NULL COMMENT 'descripcion del gasto',
  `tipo_concepto` VARCHAR(40) NULL DEFAULT 'SUCURSAL' COMMENT 'ADMINISTRATIVO|SUCURSAL',
  `des_detalle` VARCHAR(4000) NULL DEFAULT NULL COMMENT 'detalle opcional del gasto',
  `des_estado` VARCHAR(4000) NULL DEFAULT NULL COMMENT 'porque cambio de estado',
  `estado` VARCHAR(40) NULL DEFAULT 'PENDIENTE' COMMENT 'APROBADO|RECHAZADO|PENDIENTE|INVALIDO',
  `factura_tipo` VARCHAR(40) NULL DEFAULT 'EGRESO' COMMENT 'EGRESO|CONTRIBUYENTE',
  `factura_rif` VARCHAR(40) NULL DEFAULT NULL COMMENT 'rif si factura es contribuyente',
  `factura_num` VARCHAR(40) NULL DEFAULT NULL COMMENT 'mumero de factura opcinal',
  `factura_bin` VARCHAR(4000) NULL DEFAULT NULL COMMENT 'ruta/hex64 de factura por defecto si la sube, es una factura o archivo por gasto',
  `fecha_concepto` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD de cuadno es el gasto registrado',
  `fecha_registro` VARCHAR(40) NULL DEFAULT NULL COMMENT 'YYYYMMDD de cuando se creo cada entrada',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien modifico YYYYMMDDhhmmss + codger + . + ficha',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien lo creo YYYYMMDDhhmmss + codger + . + ficha',
  PRIMARY KEY (`cod_registro`))
ENGINE = InnoDB
COMMENT = 'registro de gastado por egresos con descripcion y monto';


-- -----------------------------------------------------
-- Table `elgastodb`.`subcategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`subcategoria` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`subcategoria` (
  `cod_categoria` VARCHAR(40) NOT NULL COMMENT 'CATYYYYMMDDhhmmss tabla categoria',
  `cod_subcategoria` VARCHAR(40) NOT NULL COMMENT 'SUBYYYYMMDDhhmmss',
  `des_subcategoria` VARCHAR(400) NOT NULL COMMENT 'descripcion o nombre subcategoria',
  `tipo_subcategoria` VARCHAR(40) NULL DEFAULT 'NORMAL' COMMENT 'ADMINISTRATIVA|NORMAL',
  `fecha_subcategoria` VARCHAR(40) NULL DEFAULT NULL COMMENT 'fecha creacion al usuario',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien altero YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`cod_subcategoria`))
ENGINE = InnoDB
COMMENT = 'nivel 2 clasificacion gasto';


-- -----------------------------------------------------
-- Table `elgastodb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elgastodb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `elgastodb`.`usuarios` (
  `ficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'id usuario, cedula en vnzla o id en costarica',
  `username` VARCHAR(40) NOT NULL COMMENT 'login del usuario, id del correo',
  `indicador` VARCHAR(40) NULL DEFAULT NULL COMMENT 'si entro no no y porque la ultima vez',
  `estado` VARCHAR(40) NOT NULL DEFAULT 'INACTIVO' COMMENT 'ACTIVO|INACTIVO',
  `tipo_usuario` VARCHAR(40) NULL DEFAULT NULL COMMENT 'ADMINISTRATIVO|NORMAL',
  `sessionflag` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien altero YYYYMMDDhhmmss+codger+.+user',
  `sessionficha` VARCHAR(40) NULL DEFAULT NULL COMMENT 'quien lo creo YYYYMMDDhhmmss+codger+.+user',
  PRIMARY KEY (`intranet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabla de usuarios, sus datos estan en el proyecto eldirectorio, aqui solo define su acceso';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
